#!/usr/bin/python3
from sys import argv
from math import sqrt
def factor(m):
    if m % 2 == 0:
        yield 2
        while m % 2 == 0:
            m //= 2
    for i in range(3, int(sqrt(m)) + 1, 2):
        if m % i == 0:
            yield i
            while m % i == 0:
                m //= i
    if m > 2:
        yield m


with open(argv[1]) as f:
    for line in f:
        m = int(line)
        print("{:d}=".format(m), end="")
        if m % 2 == 0:
            print("{}*2".format(m//2))
            continue
        for i in factor(m):
            print("{}*{}".format(m//i, i))
            break
        print()
